[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

startup_mode = "Maximized"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18

[general]
import = [
    "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
]
